### PR TITLE
Refine the README.md file and EDA notebook

### PR DESCRIPTION
**Pull request by chuangw6**

### CODE REVIEW

**Comment by huan-ds** [comment]
please change `conda env create --file env-abalone.yaml' to `conda env create --file env-abalone.yml' in readme file

**Comment by huan-ds** [comment]
"From the distribution plots below, we can see that all features values are not normally distributed. Specifically, most of them are highly skewed. For example, there are some outliers for the Height value. " 
-  The distributions do show skewness. but I don't think most of them are higher skewed. 
-  For outliers in Height value, add "we will exclude outliers from training dataset before building models".

**Comment by huan-ds** [comment]
That's all needs to change, thank you! @chuangw46

**Comment by chuangw6** [comment]
Aha, `yaml` was a mistake. Thanks for spotting this. The files are updated! Thank you.

**Pull request merged**
